---
linters:
    flake8:
    eslint:
        config: './eslint.config'
    csslint:
    stylelint:
        config: 'stylelintrc.json'


fixers:
    enable: true


files:
    ignore:
        - 'src/generated/*'
        - 'webroot/bower_components/*'